### ISSUE TITLE
Complication available but not in list on Watch face configuration 

### ISSUE THREAD

**Issue by nickarmstrong84** [nightscout/nightguard#12]
Hi Dirk,

As most other folks, let me start by saying great job with the watch app. It's simple to use, and I love seeing the previous day in the graph. I've been using the full app view but I would rather see just the complication in my watch face. It's listed as an available complication but I can't select it in the list when choosing a complication. Thanks.

**Comment by nickarmstrong84** [comment]
I can post screenshots if it's helps.

**Comment by nickarmstrong84** [comment]
![img_9143](https://cloud.githubusercontent.com/assets/16750267/26281188/0d3a56a0-3da5-11e7-9d83-4e1833472dd5.PNG)
![img_9144](https://cloud.githubusercontent.com/assets/16750267/26281187/0d39cd98-3da5-11e7-890c-1991c909af81.PNG)

**Comment by dhermanns** [comment]
I select the complication directly on the watch. But I could remove the complete feature since it's still not working very well. I was always struggling with the strict handling of apples battery saving policy. You simply wan't get enough Update times for the complication to work correctly.

Do you know of some complication that are able to get new data e.g. every 5 minutes? I don't think that apples allows this and therefore the complications are pretty useless for our use cases :-/.

**Comment by nickarmstrong84** [comment]
Sadly the complication for the other app I was using before I tried yours doesn't update often or at all either. You might be right, and that it's just not applicable for the refresh speed we need. No problem, thanks.
