### ISSUE TITLE
Scrolling don't work in Watch OS4

### ISSUE THREAD

**Issue by osodebailar** [nightscout/nightguard#14]
Scrolling of chart graphic do not work with Watch OS4  ( beta 1 and beta 2 )

**Comment by dhermanns** [comment]
Thanks for the hint! Right now I have no device with IOS11 / Watch OS 4 installed. So I will wait for the final version and hope that the issue doesn't exist there anymore ;-)

But feel free to contribute a fix if this is due to an incompatible change in Watch OS 4.

**Comment by dhermanns** [comment]
I could reproduce this with watchos4 and a series 2 watch. Without any changes the problem arises. A simply recompile doesn't fix it. The scrolling works fine in the simulator.

Since I don't have a real watch anymore, I will have to wait until my series 3 watch arrives ;-).

**Comment by dhermanns** [comment]
I think I found the reason for this: In watchOS 4 the focus to the crown sequencer has to be requested as late as possible. I documented it here:
https://stackoverflow.com/questions/46388908/how-to-put-the-digital-crown-back-to-work-with-watchos-4/46388909#46388909

Strange that I'm the first one who documented this on stack overflow. In the latest Version of Xcode the simulator could reproduce this behavior and after fixing it, as mentioned above, it works fine.

Since my new apple watch hasn't arrived yet, maybe someone would like to test this on a real hardware.

**Comment by dhermanns** [comment]
It should be fixed on the master branch. It will be included in the upcoming V1.4.2 Release...

**Comment by fcofernandez** [comment]
Hi
I have watch OS 4 on a series 1 and was working fine till i updated to os4 , now scroll and zoom does not respond

**Comment by dhermanns** [comment]
Yes - this was definitely an error that was introduced by watchos4. If you build nightguard using the current master branch, this should be fixed.

But I still have problems that the chart does not update anymore. This happens after an uncertain amount of time when running the app on the watch. After closing an reopening the app, scrolling/zooming und updating of the chart does work fine.

**Comment by fcofernandez** [comment]
You are right, reseting does work but it happens again after a few hours

**Comment by dhermanns** [comment]
Should be fixed now with V1.4.2 coming soon to the app store ;-)
