### ISSUE TITLE
Alarms directly on the apple watch

### ISSUE THREAD

**Issue by pebblefrijia** [nightscout/nightguard#18]
Hi! nightguard on iwatch series 3, no alarms! can you solve this problem?

**Comment by dhermanns** [comment]
Could you please elaborate in more Detail what your problem is? Alarms on the watch are not supported. Not on the series 3 or the older models.

Apple protects their battery life and therefore don't  give us cpu time to calculate alarms.
For certain app categories like running apps, this is possible now with watch os 4. Its a shame that this is not allowed for health apps :-/.

So file a request at Apple that they change their policy.

**Comment by JohanDegraeve** [comment]
Is it a problem of the iphone app that is suspended in background mode ? 
The only solution for that is to work with remote (silent) notifications, that wake up the app and give it 30 seconds time to fetch date from nightscout and also generate notifications (alarms). I would also be allowed to communicate with the iwatch

**Comment by dhermanns** [comment]
Yes - that is the problem. For the remote notifications I would need a backend that is able to send the remote notifications, right? We would need a software-as-a-service solution for this, so that anyone could easily get app specific push notifications to the watch.

Or am I missing something?

**Comment by JohanDegraeve** [comment]
No you're not missing something, I was asking to be sure I was not missing something :)

A possible solution that I used for iosxdripreader, I'll explain below why I used that.
- quickblox : https://admin.quickblox.com/
- Each time the app is installed on a device, it will get a push token from Apple and register at quickblox.
Registration at quickblox is with a unique id, (example 63B42E52-89C5-4169-8182-A16BA314A802) and with always the same password. Nobody needs to login ever, password is not known. The id must be unique to the device, because a user may delete the app and re-install it, it should be the same unique id.

- Then I have a second app, running on a spare iphone, always in the foreground, always charging. It sends a message via quickblox to each registered device, every 5 minutes.
Each device will receive the remote notification, silently and will be woken up and has 30 seconds to do up or downloads, and also calculate/generate alarms (notifications)

- To avoid that some devices need to wait  too long before being able to do a up/download, the register with a tag. There are 5 tags, one for each minute, the tag depends on the timing the reading is generated. 
The iphone will actually send a message every minute, each time with another tag, one or the first minute, the second minute, ...
Initially the device will register with "ONE", but once it has received a reading, it knows the timing of the reading and can update that tag. In this way, the delay is maximum something like 90 seconds.

It could be further refined, for instance create a tag for each interval of 15 seconds, ie 20 tags in total.

Why did I implement this ? while developing iosxdripreader and starting the NS upload, I notice that upload while in background didn't work. I started digging in the documentation and started implementing this. Upload to NS was happening with around 30-90 seconds delay. Only months later I noticed this wasn't actually necessary. iosxdripreader has a bluetooth connection with the device (G4, G5, ..), and while a connection is set up, or while the device is transmitting data, it is actually allowed to do up/downloads for about 1 minute or even longer, .. and also generate alarms.
So a few months ago I just swithced off that spare iphone that was sending the messages, and also disabled that functionality in the app.
The app that sends the messages is here : https://github.com/JohanDegraeve/pushnotification

Maybe you could re-implement some of the functionality that I did ?

There are off course some limitations
- quickblox free plan is limited in traffic to 20/s, this could be quickly reached. 
But maybe this could be upgraded to a paid plan, where users actually pay for the app.  I think this is acceptable. I might do it myself in the future, but my app isn't stable enough in the background, probably because it's not written in native objective-c or swift

depends off course how much time and effort you still want to put in your project

**Comment by dhermanns** [comment]
Hi Johan!

Thanks for your insights! I didn't now this service - it sounds great. 
What I would love to do is implement a backend that is api compatible to nightscout and that supports multiple nightscout users out-of-the-box. 

The sending of push notifications wouldn't be a big deal then.

But I think I don't have the time to do it right now :-/.

**Comment by dhermanns** [comment]
Maybe the new watchOS 4 frontmost state feature can help implement haptic alarms on the watch:
https://developer.apple.com/videos/play/wwdc2017/216/

I will play with these a bit and see if I really get 8 Minutes of time to read new values.

**Comment by dhermanns** [comment]
Upcoming 1.6.0 has an experimentally alarm feature. As soon as background updates start working, this should be really cool. But right now, the alarms will only work, if your display is on and the app is running. Keep that in mind.
