### ISSUE TITLE
Complication value does not fit and gives "2..." - font issue? 

### ISSUE THREAD

**Issue by loopy321** [nightscout/nightguard#194]
Any ideas how to fix this issue?  Mostly notice when BG is > 99.  It seems to happen randomly - i.e. not just when the time is a 4 digit ("12:00").  This is on an apple watch 4, ios 15.5, watchos 8.4.2, watchface: "Infograph Modular".  Nightguard 3.7.1.780.  
![IMG_3868](https://user-images.githubusercontent.com/1026345/172851544-d118f745-aa32-4552-8c84-58a7d621fa35.jpg)

**Comment by dhermanns** [comment]
Do you have the small version of the watch?
Do you have a screenshot of the working complication?

This is how mine looks.![image](https://user-images.githubusercontent.com/3207317/173140509-c56fa408-8834-40d4-8340-394352baa92c.png)

**Comment by loopy321** [comment]
Yes, I have the smaller version of the watch 4.  This what it looks like working ok:
![CC42C9B4-F7C0-42A5-84ED-A0C0593F4B8F](https://user-images.githubusercontent.com/1026345/173156762-c5cb6b39-bc6f-4578-b914-df14f64f2e0f.png)

**Comment by dhermanns** [comment]
![Simulator Screen Shot - 40mm Series 4 - 2022-09-18 at 19 14 31](https://user-images.githubusercontent.com/3207317/190919887-6aca0179-5a17-414b-86c5-73549fc073fd.png)

I changed the type of the circular complication. Added the update time now.
This way, more information is displayed and watchOS shrinks this automatically, so that 
everything is fully displayed.

Will be available with the next release.
