### ISSUE TITLE
WatchOS 9.1 shrank the complication!

### ISSUE THREAD

**Issue by pixelpants** [nightscout/nightguard#207]
![D17BFD87-EE79-4411-B60F-FC9B4E00E5F1](https://user-images.githubusercontent.com/3606447/201454276-600bfc2a-1711-4f11-b10b-1f5dea978260.png)
After updating the watchOS, the bg number in the complication has been shrunk down. It's absurdly small all of a sudden. See image.

**Comment by dhermanns** [comment]
Yes - turns out that apple has modified something here. We had another case
where to big values have been replaced by dots.

I can have a second look but don‘t think I can improve that much.
You can try to switch to another complication type like corner complication.



pixelpants ***@***.***> schrieb am Sa. 12. Nov. 2022 um 04:29:

**Comment by pixelpants** [comment]
I see. That’s a shame, and a little annoying on the part of Apple.

Regarding using a corner complication, is the one I’m using in the screenshot not just that? As you can see, faintly behind it, there is now a dark grey circle. I have not found a watchface where it is not circular. I’m happy to switch, if you know of one.

**Comment by dhermanns** [comment]
![image](https://user-images.githubusercontent.com/3207317/203593780-15d9a5c2-4bc9-4d7b-9f81-02791c6365e3.png)

I'm using this one. But think it is not available for older watches. So that could be the reason.

**Comment by dhermanns** [comment]
Feel free to reopen if someone has more ideas how the complications can be improved.
