### ISSUE TITLE
large rectangular complication missing

### ISSUE THREAD

**Issue by dpmusic** [nightscout/nightguard#222]
Hi, when I edit the watch face I can select the complication in the small circular windows, but it doesn't show up in the drop down list for the large, center rectangular complication. Shouldn't it be there too? watch 9.3.1, phone 16.1.1. Thanks!

**Comment by dhermanns** [comment]
Looks like Apple broke some backwards compatibility. Nightguard uses the clockkit API. Nowadays the widgetkit API is the way to go.

So we should migrate to the new API. I would bet that this will fix the incompatibilities noticed here.

**Comment by KeiraAlexandra** [comment]
Thanks for the reply. How or when this API issue will be solved? I’m a bit lost about API etc, I have no idea what you are talking about 😁

**Comment by dhermanns** [comment]
I will provide a new version which solves this. But will take some time. Its quite a rewrite of the complications.

**Comment by dhermanns** [comment]
The TestFlight is available now:
https://testflight.apple.com/join/Ub8WcpcE

Let me now if it works for you.

**Comment by KeiraAlexandra** [comment]
Hi,First of all let me thank you for the hard work you are doing!I installed the beta version and I will send you as an attachment a photo of my watch screen. I’m using modular face and middle section is BG values:- first line of BG values reading is missing space between BG value (10.1) and change of it, also +/- sign is missing- second and third line of BG values show rounded BG values and doesn’t show change at all.After about 10 min the BG values were updates and then it didn’t show change at all just the direction the BG is movingI will try some other faces later on.Best regardsKristina Viisalu-JarachOn 15. Apr 2023, at 19:13, dhermanns ***@***.***> wrote:﻿
The TestFlight is available now:
https://testflight.apple.com/join/Ub8WcpcE
Let me now if it works for you.

**Comment by dpmusic** [comment]
I would also like to say thank you for this great app! I know how much work something like this can be!

I found the new complication-



Great, thank you! 

if I can offer some feedback: 

I don’t understand what the “8m 5” lines refer to.?

I would love a choice where it’s just the top line, without the “-0.0” part (also not sure what that is...), just the age of the reading, the number, and the arrow. In a nice large font! would be great! thank you!

**Comment by dhermanns** [comment]
Nice that you are testing with mmol. This is always hard for me to do, since we are on mgdl. 
If I manually switch to mmol, with the upcoming TestFlight, it should look like:

![image](https://user-images.githubusercontent.com/3207317/232306973-f2d99e17-1f4c-41aa-8efb-8116942533b2.png)

**Comment by dhermanns** [comment]
8m is the age of this reading. This is very crucial, since background updates are still rare. So just showing a number doesn't make much sense to me. 

The +0.7 means the relative change in blood glucose compared to the value measured before.

**Comment by KeiraAlexandra** [comment]
Which watch face are you using? I don’t get 3 readings that are exact and show +/-. Best regardsKristinaOn 16. Apr 2023, at 14:32, dhermanns ***@***.***> wrote:﻿
Nice that you are testing with mmol. This is always hard for me to do, since we are on mgdl.
If I manually switch to mmol, with the upcoming TestFlight, it should look like:

**Comment by KeiraAlexandra** [comment]
After the last update that says on the large middle section ‘BG values as text’ the BG values don’t show anymore at all.Best regards KristinaOn 16. Apr 2023, at 20:38, Kristina Viisalu ***@***.***> wrote:﻿Which watch face are you using? I don’t get 3 readings that are exact and show +/-. Best regardsKristinaOn 16. Apr 2023, at 14:32, dhermanns ***@***.***> wrote:﻿
Nice that you are testing with mmol. This is always hard for me to do, since we are on mgdl.
If I manually switch to mmol, with the upcoming TestFlight, it should look like:

**Comment by dhermanns** [comment]
Hi Alexandra. You would have to wait some time until a background update has been scheduled. I'm right now testing this, too. Took in my case an hour until it showed up.

I will see whether I can force a timeline update earlier. For the circular complication its working already.

**Comment by dhermanns** [comment]
Latest TestFlight should work fine now. Let me know if you have any issues

**Comment by dpmusic** [comment]
I have download it and install the app on my iPhone, but I do not see it on my Apple Watch 3. Is there another step? Feel like I should know this….Sent from my iPhoneOn Apr 20, 2023, at 12:01 PM, dhermanns ***@***.***> wrote:﻿
Latest TestFlight should work fine now. Let me know if you have any issues

**Comment by dhermanns** [comment]
Series 3 sounds pretty old. Does it still support WatchOS 9?

Darcy Phillips ***@***.***> schrieb am So. 23. Apr. 2023 um
23:31:

**Comment by dpmusic** [comment]
I suppose that’s it then- still on os8.Sent from my iPhoneOn Apr 23, 2023, at 3:36 PM, dhermanns ***@***.***> wrote:﻿
Series 3 sounds pretty old. Does it still support WatchOS 9?

Darcy Phillips ***@***.***> schrieb am So. 23. Apr. 2023 um
23:31:

**Comment by dhermanns** [comment]
Double checked it:

https://developer.apple.com/forums/thread/712176

But yes. You will have to be on WatchOS9 to use the new Widgetkit based complications. And it doesn't seem that apple has backported them back to WatchOS9. Sorry.

**Comment by KeiraAlexandra** [comment]
Hello!Something strange is going on with middle rectangular compilation - since yesterday it doesn’t show last 3 readings, it’s just blank space on the main watch screen. When I touch the empty space of watch screen where the 3 readings used to be then it takes to BG values etc as it always did.Please see photos attached.Can I get the 3 readings back?Best regards KristinaOn 20. Apr 2023, at 22:01, dhermanns ***@***.***> wrote:﻿
Latest TestFlight should work fine now. Let me know if you have any issues

**Comment by dhermanns** [comment]
Sounds like you switched to a new nightguard Testflight version? Youshould try to reselect the complication. If that doesn't help, try to deinstall/reinstall the watch part.

**Comment by KeiraAlexandra** [comment]
Hello!With the latest Apple Watch update the BG values doesn’t show up in Modular face anymore.Is there a way to get the 3 readings back in the middle part of the watch?Best regardsKristinaOn 4. May 2023, at 23:42, dhermanns ***@***.***> wrote:﻿
Sounds like you switched to a new nightguard Testflight version? Youshould try to reselect the complication. If that doesn't help, try to deinstall/reinstall the watch part.
