### ISSUE TITLE
Upload issue to Apple Health

### ISSUE THREAD

**Issue by JohnV235** [nightscout/nightguard#255]
Nightguard has started uploading 54 entries for every second to Apple Health.  Example: at 4:45 AM it sends the same glucose reading 54 times.  Then at 4:45 AM it will send the reading 54 times.  Then at 4:46 AM, etc.  Totally messed up using Apple Health for my glucose.  Any ideas?

**Comment by JohnV235** [comment]
Thanks - I'm new to this.  Version 3.8.1.831

**Comment by dhermanns** [comment]
This is the latest App-Store Version. @sebdei could you have a look?

**Comment by sebdei** [comment]
If I remember correctly, duplication handling is done by apple health itself. Since I'm not using the App anymore, it would be nice if somebody would approve this bug. In any case I might find some time during the next few weeks.

**Comment by superevr** [comment]
First time setting up Nightguard and syncing to Apple Health. I'm really happy to have this functionality to put more of my information in one place. This is very helpful, especially when looking up historical changes and trends. 

Unfortunately I also came across this bug. Similar to the first post, Nightguard generated dozens and dozens of duplicate entries for readings. For example, one of the synced historical records for **Jan 26 at 5:50:23 PM** appears in the Apple Health Recorded Data 56 times. That is, Same glucose, same date (to the second), same source, and _nearby_ "Date Added to Health". (From **Jan 26, 2024 at 6:17:55** PM through **6:17:56 PM**)

![image](https://github.com/nightscout/nightguard/assets/2046483/b1f5410c-c293-48b0-a702-ae795d56e612)

This doesn't happen always, but it certainly floods Apple Health with duplicate data. I don't think Apple Health de-duplicates the raw data. But it will de-duplicate the information from two different apps before it displays it in a chart.

This is version 3.9.1 from the app store.

**Comment by superevr** [comment]
If it helps, the data is syncing from the Gluroo API, which is populating data for Freestyle Libre 3 via Libre Link Up.

**Comment by Parke-Bench** [comment]
Same issue here, data coming from GluRoo’s LibreLinkUp connection to my Libre 2. 

Love the NightGuard app and having my BS nums on my Apple Watch, but I had to disable the HealthKit integration because it was flooding my history with thousands of readings every hour. 

I’m not super experienced with iOS programming but I do have an Apple Developer’s Licence, and am a fairly experienced programmer in general, so if anyone wants to point me to the “likely culprit” code in the repository, I can poke around and do some diagnostics.

**Comment by lenabee92** [comment]
I have the opposite problem… my Nightguard is receiving the information correctly from Gluroo but it isn’t transmitting to Apple Health even though I have it set to do so.

**Comment by dhermanns** [comment]
Is this still an issue with V3.9.2? Had a look at the last days but can't reproduce this. If this still is an issue, it would be helpful to know how you can force this behavior.

**Comment by lenabee92** [comment]
No it seems to be working nowSent from my iPhoneOn Jul 11, 2024, at 2:50 PM, dhermanns ***@***.***> wrote:
Is this still an issue with V3.9.2? Had a look at the last days but can't reproduce this. If this still is an issue, it would be helpful to know how you can force this behavior.

**Comment by JohnV235** [comment]
Seems to be working fine now.  All entries are unique.  Thanks!

**Comment by Parke-Bench** [comment]
> Seems to be working fine now.  All entries are unique.  Thanks!

I guess 3.9.2 hasn't made it to the Canadian Apple App Store yet. I'm on 3.9.1 and it's still uploading 54 duplicate readings every minute.

**Comment by dhermanns** [comment]
Ah - my fault. 3.9.2 is on testflight only right now. So you can try that:

https://testflight.apple.com/join/Ub8WcpcE

**Comment by Parke-Bench** [comment]
I installed 3.92 and activated Nightguard again as a data source, but unfortunately it is still submitting 50 or more duplicate entries. I'm on iOS 17.5.1. ![image](https://github.com/user-attachments/assets/1b7e9402-ccc0-4787-bfd4-0a5de59e4972)

**Comment by Parke-Bench** [comment]
I reset the Sync with Apple Health and now it's working! Yay! Thank you so much for fixing this. ![image](https://github.com/user-attachments/assets/e0a1e410-55a6-4cf0-9349-6bf2466ea96f)

**Comment by dhermanns** [comment]
Very strange that a simple reset fixes this. But very valuable hint for others that experience this. Thanks to you - I didn't do anything to fix it 😉.

**Comment by cnwtech** [comment]
I’m seeing this as a NEW ISSUE for me.
I opened ticket 326 ( https://github.com/nightscout/nightguard/issues/326 ) as a result, closed as a duplicate.

As a long time programmer and system tester (long ago), after reading these comments, Nightguard should check last write date and data written BEFORE writing it again… to prevent duplicate entries being written into Apple Health (or any service, database, etc).

Relying on data TARGET to clean-up duplicate data (even if database that cleans/prevents duplicates) is not good programming practice because:
1.  It wastes data storage (in this case the iCloud user’s account)
2. Wastes programming cycles (processor, memory, battery) on source device processing same data multiple times
3. results in more data being transmitted over the network (traffic, congestion), worst yet at Apple Health when issue with 1000s of users, not just local Nightguard client … at their system processing cost
4. Depends on Apple health cleaning up the submitted data (this is a checks and balance by Apple to control misbehaved apps… imagine at data stuffing attack!) … GIGO … may be delayed in terms of housecleaning duplicate entries
5. Makes it difficult for user to review data for time period (my case, looking for glitch in extremely low glucose readings, manual deletion of duplicate entries in Apple Health not easy, take a long time to correct), impacts timeliness of data

This is a DEFECT in Nightguard…. and needs to be fixed.

Clearly, some pointer or data is not being written to update counter, or loop that writes a block of data and pointer is not updating properly, possibly due to memory corruption or pointer offset issue.  Why it happens intermittently and repetition changes for each user situation may offer clues.

It should be simple enough when writing data to Apple Health, given a table of data with a pointer, to scan first record entries, check to see if same as last data written in stored variable, then ignore if duplicate, otherwise write if new data, update info on last written data with new record info, then proceed to next row in dataset to parse using pointer (updated), and repeat the process.  Of course required checks for successful write to Apple health, etc required (re-try).  

Side note: perhaps this is where it fails… and not checked properly… when data is not written successfully (or error code assumed to be this) when it actually is written.

I would suggest looking at Nightguard code to review and hopefully fix.

I’m sure if Apple Health team was notified that an app in App Store was writing duplicate data for 1000s of users they would have an issue with it (above points) as well as some others regarding terms of use/access and best coding practices.

Comments?

**Comment by cnwtech** [comment]
Of course another way (than Nightguard tracking last data written locally on what date) would be to query Apple Health data to see if new data to be written has already been written in the past, before deciding to write it again versus the first place.     

I’m not sure how Nightguard receives data stream from NightScout server… does this process allow duplicates to be received, as example?   Maybe this needs some logic before sending to Apple Health… and fix it earlier in the process… more efficient and effective.   Stop duplicate data earlier…

**Comment by dhermanns** [comment]
As mentioned above, the developer of the feature left the project. My time is very limited right now and I wasn't able to reproduce this.

So as a long time developer, a Pull Request from you is very welcome.

The idea of checking duplicates before sending again is great. Could cause some performance issues but would definitely fix this.

**Comment by dhermanns** [comment]
Nightguard keeps the nightscout data already deduplicated in app storage. So this should not be the issue.
