### ISSUE TITLE
Watch OS 8 support?

### ISSUE THREAD

**Issue by savek-cc** [nightscout/nightguard#273]
Hi!
As you mention that the watch app is specifically compiled for watch OS 10: does this mean that you dropped support for older apple watches with watch OS 8?
At least the watch app seams to be gone since the last update.

**Comment by savek-cc** [comment]
In case the latest.version dropped support for wear os 8: could you publish the old version as "legacy" or so?

**Comment by dhermanns** [comment]
Hi! WatchOS9 and higher is the latest Version that is supported. You can check out all old versions via github and install the old versions on your own.

But I cannot support any old version. Its not done by adding a legacy version to the app store. Every version needs care and since this is a non profit project, I don't have the time to support multiple versions. Sorry.

**Comment by savek-cc** [comment]
Thanks for the heads up - and I guess thanks to Apple by not allowing to downgrade to a compatible version. Stinks as the iPhone was upgraded to iOS 17 - but the watch 3 bought 2 yrs ago doesn't get watch OS 10...

**Comment by dhermanns** [comment]
You don't need to pay for the dev licence. You can do local deployments without it.

Series 3 was released 2017. So always take care of the first release date when buying.
