### ISSUE TITLE
Looks like the time change killed nightguard on my phone

### ISSUE THREAD

**Issue by cjbeck** [nightscout/nightguard#53]
Nightguard won't load on my phone after the time change. When it loads, the current value shows, but the UI is unresponsive and I can't do anything with the app. The app on the watch also crashes.

**Comment by dhermanns** [comment]
Hi! You could try the beta version. Florian changed there something regarding the daylight savings. Would be just a try...

**Comment by cjbeck** [comment]
So, I compiled the latest version of the code in a simulator and it does work with my nightscout site. I'm trying to get it compiled and installed on my phone and watch, but (as you might expect), getting all the certs and whatnot working is not straight-forward.

**Comment by florianpreknya** [comment]
@cjbeck you should try the new beta version or... reinstall the store app, it should work now. I had the same problem, we share some similar timezone properties, it seems... There was a bug that got the app running in a loop when trying to do some operations on the daylight saving transition hour. The problem persists because those dates are still on your device, so... you need to get rid of them. The simplest way is to reinstall the app. 
The problem was fixed, a new release is on the way... so no more troubles (I hope!) for the next daylight saving date.

**Comment by cjbeck** [comment]
@dhermanns, I'd love to be on the beta cycle. My email is cj.beck@gmail.com. Florian, looks like the re-install with the new version worked. Thanks!
