### ISSUE TITLE
Watch synchronization seems to be broken

### ISSUE THREAD

**Issue by dhermanns** [nightscout/nightguard#63]
In the latest beta, the synchronization of the URI seems to be broken. Everything seems to work after upgrading, but after deinstallation/reinstalling of the watch part, the watch keeps the "Requesting data from phone" screen.

@florianpreknya : Should I have a look at it during weekend?

**Comment by florianpreknya** [comment]
Sure, you could.
How can I reproduce it? I tried but I'm not sure if this is your scenario.
I uninstalled the watch part from the Watch application, then reinstalled it. It showed the "Requesting data from phone" for a longer time, deactivated (because I didn't interacted with it), but on reactivation it completed and showed the data correctly. Did you do something different?

**Comment by dhermanns** [comment]
No - that‘s exactly my case.

**Comment by dhermanns** [comment]
If I click on Info - the URI is still empty. Even after interacting with the watch.

**Comment by dhermanns** [comment]
This morning the watch part was deinstalled automatically. After reinstalling the sync is working fine now.

Strange - I will have an eye on it. Maybe just a watchos glitch...

**Comment by florianpreknya** [comment]
Tried it a few more times, also an extreme case (I killed the phone nightscout app before reinstalling the watch part) - all were successful, the sync worked after starting the newly reinstalled watch app.

**Comment by florianpreknya** [comment]
I can imagine a connection failure between the phone and watch, but that's a temporary problem. The sync will run on each activation of the watch app, so when the connection problems are solved, the sync should work.

**Comment by dhermanns** [comment]
Works great now!
