### ISSUE TITLE
Snooze problem

### ISSUE THREAD

**Issue by armin999** [nightscout/nightguard#66]
Please be careful when setting a snooze. After snoozing for 30minutes few times, went to sleep and somehow the snooze function went to 24hr snooze automatically. I swear I did not touch the 24hr snooze option but it still selected that option when I suddenly woke up. Thank god the level did not go low.  First I thought maybe I accidentally hit the 24hr during sleep but then it happened twice again and this time I captured the screenshot. I think there is a programming or coding error in the app where it automatically resets to 24hrs after few short snoozes. 
I attached 2 photos showing how snooze function automatically goes to high snooze

Is this a malfunction or coding error in the app?

![3DB4CDAB-AC3E-4813-990A-618CF2E70DFF](https://user-images.githubusercontent.com/10148160/55832977-b78c9d80-5ae4-11e9-8400-91240ccaf9c4.png)
![3843A0D7-3B6F-4170-BECC-FCFA7D6F3C60](https://user-images.githubusercontent.com/10148160/55832978-b78c9d80-5ae4-11e9-8242-c6e44df13ab9.png)

**Comment by armin999** [comment]
App version 2.5.447
iPhone 6 iOS version 12.1

**Comment by dhermanns** [comment]
Hi!

I touched multiple 30min snoozes.
But it keeps counting down.

Can you reproduce this?

armin999 <notifications@github.com> schrieb am Di. 9. Apr. 2019 um 22:38:

**Comment by dhermanns** [comment]
I had the same problem when my phone was too close to my bed. I will see whether we can replace the snooze button with a „slide to unlock“ one.

But try to reproduce it - can still be the case that we have a bug here.

**Comment by florianpreknya** [comment]
I have analyzed the code for finding a suspect in this case. Couldn't find anything, the snoozing code is localized and relatively simple, all the buttons and logic that ultimately call snooze are doing the right thing. 
@armin999 do you use an apple watch? Did it happen with the phone near you?

I can confirm it happened to me also for a few times, that's why I'm keeping now the phone at some distance from my bed. It is very easy to accidentally hit snooze, the next features I'm thinking about are the following:
* add some "friction" on snooze
Some ideas: long press, slide to unlock, drag the button to some (random) other place on the screen, respond to a simple question (math question, color/shape recognition, etc), enter your passcode, etc.
Ideally, snoozing should require a level of consciousness from the user (otherwise the brain will learn the shortcuts and hit snooze with eyes shut). 
There are some good alarm apps that can provide some ideas, I have installed one called Alarmy and it can be configured to solve some missions on Snooze (to be sure your awake). 
Another idea I have seen in an app is an interactive long press: the app is telling you to press a button for 2 seconds, then, while keeping the button down, it changes the message and tells you to keep it a little longer (random every time)... to keep your attention and awareness when releasing it. This idea can be composed with "sliding to unlock" or drag to other random position... and you got a very "hard to accidentally hit" Snooze button.

* 24h rolling logs that will track all the important user & app actions 
I prefer logs rather than analytics because logs are more lightweight, are kept on the device not on a server - and btw, where to keep analytics account settings in an open source project? -,  can be viewed by the user, etc.

Waiting for your feedback on this topic.

**Comment by dhermanns** [comment]
@florianpreknya: What I would like is something like that:
https://github.com/maail/MMSlidingButton

That would reduce accidental snoozes to a minimum.

@armin999 : The two screenshots you gave are from different days - right? So they show just a 24h hours and a 6h snooze. But they are not associated with each other. @florianpreknya : A simple local logging would be indeed very helpful to see what has happend here.

@armin999: Would be indeed very interesting if you are wearing the apple watch at night.

**Comment by florianpreknya** [comment]
@dhermanns that sliding button was also one of my options. Do you mind if I’ll give it a try?

**Comment by armin999** [comment]
I do not have Apple Watch. Just the iPhone 6.
Logging would be a good idea so we can see if the snooze was done by human interaction or rolled over automatically like in my case.
If logs can be available on the App itself would be useful.
Secondly, if you are testing out the Snooze option, snooze it 2-3 time for 30minutes and then let the clock run down till it expires and see if it rolls over to 24hrs like it did on my iPhone. That was scary.
For now, I have switched to "Nightscout" App with version 0.10.2-release-20171201 which is also loaded on my phone.

**Comment by dhermanns** [comment]
Did you let the 2-3 30 minute snoozes run through, too? Or did you cancel
them before the snooze endet?

**Comment by dhermanns** [comment]
Double-checked the code doing the Snooze Time-Management. Can't see how a countdown of an existing Timer could start another longer one.

Further more did four 30 minute snooze. All timed down normally.
@florianpreknya: I will have some time next week. I could implement the above "slide-to-snooze" Button.

**Comment by florianpreknya** [comment]
@dhermanns Great! Then I’ll focus on logging if I’ll have some time.

**Comment by armin999** [comment]
I let the snooze run down to 0 and if the level is still HIGH, I would snooze again for 30minutes and let it run down to 0 again. 
The snapshot I uploaded are from 2 different days.
Logging locally would be a good idea to see how many times snooze was activated and what time.
As for snooze buttons, I think I am quite happy with the button and the sizes and the Timer options, i.e. 5, 10, 15, 30 etc........it is easy to press whatever option I want and it is large enough for a finger or thumb push. 
Here is another great idea.....to make it safe proof.......so no user can accidentally set Long snooze and end up going Low or in hypoglycemia condition, You simply make it mandatory audible alarm at LOW setting. For an example if my LOW Alarm is set to 4.5mmol/l then ALL snooze options and Sound options will be overridden and the Audible Alarm will sound no matter what. I think this will be very very safe. If this can enabled, would be great.
By the way, it is a a great app with lot of options under Alarms and Preferences.

I'll wait for your reply.

**Comment by dhermanns** [comment]
Did you had the problem again - or did it vanished after you placed your phone in further distance to your bed?

If the latter was the case, this pull request I created could help:
#68 

It will be available for beta testing soon...

**Comment by armin999** [comment]
I have been using Nightscout app. But if you can put a safeguard against LOW alarm and it overrides the snooze settings as soon as LOW level is reached, I will test.

**Comment by dhermanns** [comment]
No - we don‘t have such a safeguard.

**Comment by dhermanns** [comment]
The feature is ready for beta testing soon using test flight.
